---
 - pause: 
     seconds: 20 

 - name: Process check
   shell: ps -ef 
   register: reg_proc
 - debug: msg="{{ reg_proc.stdout }}"

 - name: http curl test -- without following redirection
   shell: curl http://localhost/hello
   args:
    warn: false
   register: result
 - debug: msg="{{ result.stdout_lines }}"

 - name: http curl test -- follow redirection
   shell: curl -L -k http://localhost:80/hello
   args:
    warn: false
   register: follow
 - debug: msg="{{ follow.stdout_lines }}"

 - name: https curl test
   shell: curl -k https://localhost/hello
   args:
    warn: false
   register: ssl_out
 - debug: msg="{{ ssl_out.stdout }}"

